### ISSUE TITLE
The webview algorithm should have equal padding

### ISSUE THREAD

**Issue by AaskaShah** [rajpinge/Programming_Club_App#2]
The algorithm should start after the same spacing as in right and left.
For example, here spacing between algorithm of the day and geeks for geeks should be same as in left and right.
![screenshot from 2016-01-08 22 41 14](https://cloud.githubusercontent.com/assets/11875217/12204560/e02689a4-b65a-11e5-8447-f95d3ff7fda4.png)

**Comment by omkar13** [comment]
pull request on issue sent
